<?php
require dirname(__DIR__) . '/bootstrap.php';
use App\Support\Database;

$fixtures=[];$competitions=[];
try{$pdo=Database::connection();$fixtures=$pdo->query("SELECT f.provider_id,f.kickoff,f.status,f.home_score,f.away_score,f.stats_imported,c.name competition_name,c.country_name,c.logo competition_logo,h.name home_name,h.logo home_logo,a.name away_name,a.logo away_logo FROM fixtures f JOIN competitions c ON c.id=f.competition_id JOIN teams h ON h.id=f.home_team_id JOIN teams a ON a.id=f.away_team_id WHERE c.prediction_enabled=1 AND f.kickoff>=DATE_SUB(UTC_TIMESTAMP(),INTERVAL 1 DAY) ORDER BY f.kickoff ASC LIMIT 30")->fetchAll(PDO::FETCH_ASSOC);$competitions=$pdo->query("SELECT name,country_name,logo FROM competitions WHERE prediction_enabled=1 ORDER BY country_name,name LIMIT 12")->fetchAll(PDO::FETCH_ASSOC);}catch(Throwable){}
function e(mixed $v):string{return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function dt(string $v,string $format):string{try{$d=new DateTime($v,new DateTimeZone('UTC'));$d->setTimezone(new DateTimeZone('Europe/Berlin'));return $d->format($format);}catch(Throwable){return '—';}}
function initials(string $v):string{$p=preg_split('/\s+/',trim($v));return strtoupper(substr($p[0]??'',0,1).substr($p[1]??'',0,1));}
$groups=[];foreach($fixtures as $f){$groups[$f['competition_name']][]=$f;}
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>TukiScore — Football Intelligence</title><meta name="description" content="Football predictions, probabilities, match statistics and model intelligence."><script src="https://cdn.tailwindcss.com"></script><script defer src="https://cdn.jsdelivr.net/npm/alpinejs@3.x.x/dist/cdn.min.js"></script><style>[x-cloak]{display:none!important}body{font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}.scrollbar-none::-webkit-scrollbar{display:none}</style></head>
<body class="bg-[#f3f4f6] text-[#17191c] min-h-screen" x-data="{mobile:false}">
<header class="bg-white border-b border-slate-200 sticky top-0 z-40"><div class="h-16 max-w-[1500px] mx-auto px-4 lg:px-7 flex items-center gap-6"><a href="/" class="font-black text-2xl tracking-[-.06em] whitespace-nowrap">TUKI<span class="text-emerald-500">SCORE</span></a><div class="hidden md:flex flex-1 max-w-2xl h-10 bg-slate-100 rounded-xl items-center px-4 gap-3 text-slate-400"><span>⌕</span><input class="bg-transparent outline-none text-sm w-full" placeholder="Search teams, matches, competitions..."></div><div class="ml-auto flex items-center gap-2"><button class="w-10 h-10 rounded-xl bg-slate-100 text-slate-500">☆</button><button @click="mobile=!mobile" class="lg:hidden w-10 h-10 rounded-xl bg-slate-100">☰</button></div></div><div class="border-t border-slate-100"><nav class="max-w-[1500px] mx-auto px-4 lg:px-7 h-12 flex items-center gap-7 text-sm font-semibold text-slate-500 overflow-x-auto scrollbar-none"><a class="text-emerald-600" href="/">⚽ Matches</a><a href="#predictions">✦ Predictions</a><a href="#trends">↗ Trends</a><a href="#models">▦ Models</a><a href="#performance">◎ Performance</a><a href="#methodology">⚙ Methodology</a></nav></div></header>
<div class="max-w-[1500px] mx-auto lg:grid lg:grid-cols-[230px_minmax(0,1fr)_250px] gap-4 px-4 lg:px-5 py-4">
<aside class="hidden lg:block"><div class="text-[11px] font-bold mb-3 px-2">TOP COMPETITIONS</div><div class="bg-white rounded-2xl border border-slate-200 overflow-hidden"><div class="px-4 py-3 font-bold flex items-center gap-2 border-b border-slate-100"><span class="text-emerald-500">⚽</span> Football</div><?php foreach(array_slice($competitions,0,8) as $c):?><a href="#" class="flex items-center gap-3 px-4 py-3 hover:bg-slate-50"><div class="w-8 h-8 rounded-lg bg-slate-50 grid place-items-center overflow-hidden"><?php if($c['logo']):?><img src="<?=e($c['logo'])?>" class="w-6 h-6 object-contain"><?php else:?><span class="text-[10px] font-black text-slate-400"><?=e(initials($c['name']))?></span><?php endif;?></div><div class="min-w-0"><div class="text-xs font-semibold truncate"><?=e($c['name'])?></div><div class="text-[10px] text-slate-400 mt-0.5"><?=e($c['country_name']?:'International')?></div></div></a><?php endforeach;?></div></aside>
<main class="min-w-0"><section class="mb-4"><div class="flex gap-3 overflow-x-auto scrollbar-none pb-1"><?php foreach(array_slice($competitions,0,8) as $i=>$c):?><div class="shrink-0 w-28 h-20 rounded-2xl p-3 <?= $i===0?'bg-emerald-600 text-white':'bg-white border border-slate-200' ?>"><div class="text-[10px] font-bold truncate"><?=e($c['name'])?></div><div class="mt-3 flex justify-between items-end"><span class="text-[10px] opacity-70 truncate max-w-[55px]"><?=e($c['country_name']?:'INT')?></span><?php if($c['logo']):?><img src="<?=e($c['logo'])?>" class="w-7 h-7 object-contain"><?php endif;?></div></div><?php endforeach;?></div></section>
<section class="bg-white border border-slate-200 rounded-2xl overflow-hidden"><div class="p-5 border-b border-slate-100 flex flex-col sm:flex-row sm:items-center justify-between gap-4"><div><h1 class="font-extrabold text-xl">Football Matches & Predictions</h1><p class="text-xs text-slate-400 mt-1">Fixtures, results and model intelligence</p></div><div class="flex items-center bg-slate-100 rounded-xl p-1 text-xs font-semibold"><button class="bg-white shadow-sm rounded-lg px-3 py-2">All</button><button class="px-3 py-2 text-slate-500">Live</button><button class="px-3 py-2 text-slate-500">Upcoming</button></div></div>
<div class="px-4 py-3 border-b border-slate-100 flex gap-2 overflow-x-auto scrollbar-none"><?php foreach([-1,0,1,2,3] as $offset):$d=(new DateTimeImmutable('today'))->modify(($offset>=0?'+':'').$offset.' day');?><button class="shrink-0 rounded-xl px-4 py-2 text-center <?= $offset===0?'bg-emerald-500 text-white':'bg-slate-50 text-slate-500' ?>"><div class="text-[10px] font-semibold"><?= $offset===0?'TODAY':strtoupper($d->format('D')) ?></div><div class="text-xs font-bold mt-0.5"><?=$d->format('d M')?></div></button><?php endforeach;?></div>
<?php if(!$groups):?><div class="py-20 text-center"><div class="w-14 h-14 mx-auto rounded-full bg-emerald-50 grid place-items-center text-2xl">⚽</div><h2 class="font-bold mt-4">No fixtures available yet</h2><p class="text-sm text-slate-400 mt-1">The collector is preparing supported competition data.</p></div><?php else:?><?php foreach($groups as $competition=>$matches):?><div class="border-b border-slate-100 last:border-0"><div class="bg-slate-50 px-4 py-2.5 flex items-center justify-between"><div class="text-xs font-bold"><?=e($competition)?></div><div class="text-[10px] text-slate-400"><?=count($matches)?> matches</div></div><?php foreach($matches as $f):?><a href="match.php?id=<?=urlencode($f['provider_id'])?>" class="grid grid-cols-[50px_minmax(0,1fr)_70px] sm:grid-cols-[65px_minmax(0,1fr)_100px_85px] items-center gap-3 px-4 py-3 border-t border-slate-100 hover:bg-emerald-50/40 transition"><div class="text-center"><div class="text-xs font-bold"><?=e(dt($f['kickoff'],'H:i'))?></div><div class="text-[9px] text-slate-400 mt-1"><?=e(dt($f['kickoff'],'d M'))?></div></div><div class="min-w-0 space-y-2"><div class="flex items-center gap-2"><?php if($f['home_logo']):?><img src="<?=e($f['home_logo'])?>" class="w-5 h-5 object-contain"><?php else:?><span class="w-5 h-5 rounded-full bg-slate-100 grid place-items-center text-[7px] font-bold"><?=e(initials($f['home_name']))?></span><?php endif;?><span class="text-sm font-semibold truncate"><?=e($f['home_name'])?></span></div><div class="flex items-center gap-2"><?php if($f['away_logo']):?><img src="<?=e($f['away_logo'])?>" class="w-5 h-5 object-contain"><?php else:?><span class="w-5 h-5 rounded-full bg-slate-100 grid place-items-center text-[7px] font-bold"><?=e(initials($f['away_name']))?></span><?php endif;?><span class="text-sm font-semibold truncate"><?=e($f['away_name'])?></span></div></div><div class="text-center font-black text-sm"><?= $f['home_score']!==null?e($f['home_score'].' : '.$f['away_score']):'<span class="text-slate-300">—</span>' ?></div><div class="hidden sm:block text-right"><span class="inline-flex rounded-lg px-2.5 py-1 text-[10px] font-bold <?= $f['stats_imported']?'bg-emerald-100 text-emerald-700':'bg-slate-100 text-slate-500' ?>"><?= $f['stats_imported']?'DATA READY':'PREVIEW' ?></span></div></a><?php endforeach;?></div><?php endforeach;?><?php endif;?></section>
<section id="predictions" class="grid sm:grid-cols-3 gap-3 mt-4"><div class="bg-white rounded-2xl border border-slate-200 p-5"><div class="text-xs text-slate-400">Prediction markets</div><div class="font-extrabold text-xl mt-2">1X2 + Goals</div><p class="text-xs text-slate-400 mt-2">More markets activate as models are validated.</p></div><div class="bg-white rounded-2xl border border-slate-200 p-5"><div class="text-xs text-slate-400">Model confidence</div><div class="font-extrabold text-xl mt-2">0–100 Index</div><p class="text-xs text-slate-400 mt-2">Separate from the probability itself.</p></div><div class="bg-white rounded-2xl border border-slate-200 p-5"><div class="text-xs text-slate-400">Transparency</div><div class="font-extrabold text-xl mt-2">Tracked history</div><p class="text-xs text-slate-400 mt-2">Prediction versions remain auditable.</p></div></section></main>
<aside class="hidden lg:block"><div class="bg-white rounded-2xl border border-slate-200 p-4 sticky top-32"><h2 class="font-extrabold">TukiScore Intelligence</h2><p class="text-xs text-slate-400 mt-1">Model status</p><div class="mt-4 rounded-xl bg-emerald-50 border border-emerald-100 p-4"><div class="flex items-center gap-2 text-xs font-bold text-emerald-700"><span class="w-2 h-2 rounded-full bg-emerald-500"></span> DATA ENGINE ACTIVE</div><p class="text-xs text-slate-500 leading-5 mt-3">Historical match data is being collected and validated before public forecasts are published.</p></div><div class="mt-4 space-y-3"><?php foreach([['Result model','Preparing'],['Goals model','Preparing'],['Shots model','Queued'],['Corners model','Queued']] as $m):?><div class="flex items-center justify-between text-xs"><span class="font-semibold"><?=$m[0]?></span><span class="text-slate-400"><?=$m[1]?></span></div><?php endforeach;?></div><a href="#performance" class="mt-5 block text-center rounded-xl bg-[#17191c] text-white text-xs font-bold py-3">View model performance</a></div></aside>
</div><footer class="max-w-[1500px] mx-auto px-5 py-8 text-xs text-slate-400 flex justify-between"><span>© <?=date('Y')?> TukiScore</span><span>Probabilities are estimates, not guarantees.</span></footer></body></html>